### ISSUE TITLE
Application messages

### ISSUE THREAD

**Issue by mfk99** [AnttiVainikka/DistributedProject#3]
Messages for implementing functionalities:
- pause (anyone -> master, master -> everyone)
When a lobby member wants to pause playback, it sends this to master. Master will
send it to everyone once the previous message sent by it has been processed by all
members.
- resume (anyone -> master, master -> everyone)
Same as pause, expect this resumes playback. We use two separate message types
even though the UI will likely be a toggle button, because this allows two people to
pause the music at the same time without immediately resuming playback.
- skip to timestamp (anyone -> master, master -> everyone)
Skip to timestamp. Master relays this like pause and resume messages.
- modify playlist (anyone -> master, master -> everyone)
Append a new song to the playlist. This should be preceded by sending an audio file
to everyone.
- skip to next song (anyone -> master, master -> everyone)
Skip to the next song in the playlist

**Comment by bensku** [comment]
Mostly functional, but skip to timestamp needs to be implemented and skip to next song has minor bugs.
